### ISSUE TITLE
Problemi sul tutorial

### ISSUE THREAD

**Issue by DrOliver94** [suicyde/Platoon#13]
1. Primo messaggio: il mazzo di carte non si vede
2. Secondo messaggio: "Quando tutte le carte vengono inserite, si può proseguire premendo Ok": l'utente è portato a premere subito ok senza leggere il resto del messaggio, spostare la frase in fondo
3. Il tasto di *Start fight* non è tradotto
4. Quarto messaggio: ”il giocatore che non ha scelto gli slot” sarebbe da scrivere meglio in ”il giocatore in difesa”
5. Dal tutorial si può capire che si può solo far scontrare solo gli slot che si trovano l'uno di fronte all'altro. Si potrebbe pensare a una modifica del tutorial per togliere tale dubbio
6. animazioni non ben gestite (le carte girano ma i baloon compaiono subito e coprono l'animazione)
7. Il jolly non può stare da solo: si capisce dal tutorial?

**Comment by Akotokoyo** [comment]
1. Frega nulla XD
2. Ad un certo punto, se uno non legge durante un tutorial, allora cosa lo fa a fare? XD
3. Fixato
4. Fixato
5. Mh non sono così convinto XD Al massimo si aggiunge un testo.
6. Notato, si potrebbe fare un attesa.
7. Fixato
