### ISSUE TITLE
Online Caso di Tempo Scaduto

### ISSUE THREAD

**Issue by Akotokoyo** [suicyde/Platoon#41]
Situazione aggiornata 08/09/19:
- il mio avversario abbandona mentre io sto ancora selezionando gli slot da scontrare, lui esce, io premo il tasto ok, e rimane in attesa della mossa dell'avversario.

Situazione:
- Giocano A e B. 
è il turno di A, B rimane in attesa, il tempo passa, e B vince a tavolino perchè A si stava guardando le spalle.
B Esce tutto contento perchè ha vinto.
A Esce dopo, premendo il bottone OK perchè ha perso per abbandono.
Conclusioni:
- B si trova ancora dentro la lobbies e UserInLobby, ma attenzione, si trova ancora nella tabella GAMES! ERRORE
- A è giustamente tornato nella home, non è più in Games, UserInLobby e lobbies! Quindi la gestione di A è CORRETTA.

**Comment by DrOliver94** [comment]
Si potrebbe eliminare la tupla in Games dell caller_user in game.js:500, controllare che non faccia danni con altre chiamate

**Comment by DrOliver94** [comment]
Fatto, ok con le chiamate. Ulteriori test fanno comunque piacere

**Comment by DrOliver94** [comment]
Caso situazione aggiornata
Test1: uscito da editor, premuto ok sul cellulare, il client dà errore di connessione e va in loop chiamando ripetutamente /fightStatus
Test2: uscito da cell, editor rimane in attesa e attende indefinitamente: male. Controllare se c'è un timer che non sta funzionando o se è rimasta un'idea non implementata. Altrimenti si può gestire la situazione, constrollando lo stato di abbandono in /fightStatus
Test3; uscito da editor. Il cell si appende come test2. Ovviamente non riesco a riprodurre test1 :'(
