### ISSUE TITLE
Informativa privacy

### ISSUE THREAD

**Issue by DrOliver94** [suicyde/Platoon#69]
- [x] Sul Database, aggiungere una colonna "policyAccepted" NOT NULL.
- [x] Inserire un breve messaggio con checkbox alla registrazione, da far accettare agli utenti, con un link alla pagina  del sito del gioco dove si trova tutto il testo(link dentro un bottone "Privacy Policy").
- [x] Fare paginetta web dove mettiamo tutti i diritti sulla privacy.
- [x] Modificare alla chiamata di registrazione per gestire la memorizzare su db.

**Comment by Akotokoyo** [comment]
[PlatoonPolicy.txt](https://github.com/suicyde/Platoon/files/3771046/PlatoonPolicy.txt)
