### ISSUE TITLE
Gestione vincitore e perdente durante la fine di una partita

### ISSUE THREAD

**Issue by Akotokoyo** [suicyde/Platoon#71]
Pare che quando si finisce la partita, un giocatore torna nella lobby, l'altro invece va nella lobby list(aggiornata)

**Comment by DrOliver94** [comment]
Per un qualche motivo il client chiama /exitLobby, indago

**Comment by DrOliver94** [comment]
Cosa alquanto stupida: premendo su Skip sull'AD farlocco nell'editor di Unity, il pulsante Exit prende anche lui il click e fa uscire dal gioco. Nel dubbio, disattivo il button quando viene mostrato l'ad
