### ISSUE TITLE
timer inizio gioco online

### ISSUE THREAD

**Issue by Akotokoyo** [suicyde/Platoon#91]
è successo che giocando online contro molli, metto le carte, e tocca a lui, pare che:
- il mio timer sia partito da 10 e non da 40, solo quando iniziavo io, riprodotto più volte

**Comment by DrOliver94** [comment]
Ho messo un resetValues tattico che mi pare abbia sistemato la situazione, controlla meglio quando puoi, che dovrei aver azzeccato come riprodurre il bug pre-patch ma non ne sono sicurissimo
